### ISSUE TITLE
macos无法获取到校园网IPV6地址

### ISSUE THREAD

**Issue by Leo-Lionni** [XiaoliChan/available-ipv6-hosts#7]
坐标，北京科技大学；机器是黑苹果， 网线接入 路由器（路由器支持ipv6)；需要用浏览器登入202.204.48.66进行验证，有时候可以获得v6，有时候“仅ipv4”。
![image](https://user-images.githubusercontent.com/35078844/64609854-71739700-d400-11e9-961d-d77ec16b9fe0.png)
学校提供了windows系统下如何获得Ipv6地址的方法， 很好使。但是在mac下，不知道咋办了。
特来请教一下。

**Comment by XiaoliChan** [comment]
莫得mac /哭
